app:
  reset-password-url: http://localhost:5173/core/reset-password-request

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info,metrics,httptrace
        exclude: beans,env
